### ISSUE TITLE
CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by kallewoof** [tdrussell/qlora-pipe#51]
After upgrading to latest deepspeed (for the `dynamic_shape` param) and running a training session, I encountered this error at step 61:
```
[rank1]:[E107 10:50:18.780482185 ProcessGroupNCCL.cpp:1504] [PG 0 (default_pg) Rank 1] Process group watchdog thread terminated with exception: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at /opt/conda/conda-bld/pytorch_1717918860194/work/c10/cuda/CUDAException.cpp:43 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7725d5f76e96 in /miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7725d5f25d10 in /miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7725d7d4df08 in /miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x56 (0x7725809e8cd6 in /miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0xa0 (0x7725809ede90 in /miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #5: c10d::ProcessGroupNCCL::watchdogHandler() + 0x1da (0x7725809f4bda in /miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #6: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x10c (0x7725809f701c in /miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0xd3e95 (0x7725d18f0e95 in /miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/torch/lib/../../../.././libstdc++.so.6)
frame #8: <unknown function> + 0x94ac3 (0x7725da294ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #9: <unknown function> + 0x126850 (0x7725da326850 in /lib/x86_64-linux-gnu/libc.so.6)

terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG 0 (default_pg) Rank 1] Process group watchdog thread terminated with exception: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at /opt/conda/conda-bld/pytorch_1717918860194/work/c10/cuda/CUDAException.cpp:43 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7725d5f76e96 in /miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7725d5f25d10 in /miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7725d7d4df08 in /miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x56 (0x7725809e8cd6 in /miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0xa0 (0x7725809ede90 in /miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #5: c10d::ProcessGroupNCCL::watchdogHandler() + 0x1da (0x7725809f4bda in /miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #6: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x10c (0x7725809f701c in /miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0xd3e95 (0x7725d18f0e95 in /miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/torch/lib/../../../.././libstdc++.so.6)
frame #8: <unknown function> + 0x94ac3 (0x7725da294ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #9: <unknown function> + 0x126850 (0x7725da326850 in /lib/x86_64-linux-gnu/libc.so.6)

Exception raised from ncclCommWatchdog at /opt/conda/conda-bld/pytorch_1717918860194/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1510 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7725d5f76e96 in /miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xe7e0bc (0x77258067e0bc in /miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0xd3e95 (0x7725d18f0e95 in /miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/torch/lib/../../../.././libstdc++.so.6)
frame #3: <unknown function> + 0x94ac3 (0x7725da294ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #4: <unknown function> + 0x126850 (0x7725da326850 in /lib/x86_64-linux-gnu/libc.so.6)

[2025-01-07 10:50:18,997] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 67732
[2025-01-07 10:50:20,214] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 67733
[2025-01-07 10:50:20,214] [ERROR] [launch.py:325:sigkill_handler] ['/miniconda3/envs/qlora-pipe/bin/python', '-u', 'train.py', '--local_rank=1', '--deepspeed', '--deepspeed_config', 'examples/ds_config.json', '--config', 'examples/config.toml'] exits with return code = -6
```

The issue is possibly in deepspeed land, so I am now retrying with deepspeed downgraded to 0.15.0, which is the earliest release that includes `dynamic_shape`. If this fixes the issue, I will close this and report as a regression there.

**Comment by kallewoof** [comment]
I crashed again, on exactly the same step. The error was more helpful this time:
```
[rank0]:   File "/home/zwoc/workspace/miniconda3/envs/qlora-pipe/lib/python3.12/site-packages/deepspeed/runtime/pipe/engine.py", line 859, in _exec_backward_pass
[rank0]:     assert len(out_tensors) == len(grad_tensors)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
And looking closer, this is definitely not right:
```
before GAS splitting, input_ids shape: torch.Size([12, 5440]), total tokens: 65280
```
I am doing a 16384 context run. This may be an issue on my customizations so I am rerunning the code from the main branch with the synchronized checkpoints patch only.

**Comment by kallewoof** [comment]
Crashed again, same spot, the CUDA internal error one this time, but I assume the issue is the same. So, it's not my customizations.

**Comment by kallewoof** [comment]
Next crash showed a different trace, this time inside flash-attn, so trying to upgrade that.

**Comment by kallewoof** [comment]
The crash sporadically hits the len issue, and sporadically does not. Adding some debug lines, this is what I am seeing:

Firstly, this is for a "working" example:
```
===========================================================================================
UNFILTERED OUTPUTS: 6
0 FP: tensor([[[ 6.8824e-25,  5.5318e-24, -2.9856e-24,  ..., -7.4963e-24,
           4.4978e-24,  2.0938e-24],
         [ 2.9102e-01,  8.4375e-01, -3.2617e-01,  ..., -8.3008e-03,
           1.6504e-01,  4.9023e-01],
         [-8.6719e-01, -6.4062e-01,  2.5781e-01,  ..., -6.7188e-01,
           2.0020e-02,  1.2988e-01],
         ...,
         [-2.0605e-01, -1.4844e-01, -3.0469e-01,  ...,  1.2695e-02,
          -6.0303e-02, -5.1953e-01],
         [-1.0352e-01, -1.2451e-01, -3.5547e-01,  ..., -4.0039e-01,
          -5.3516e-01, -2.0020e-01],
         [-1.7188e-01,  1.8652e-01,  2.1191e-01,  ...,  2.6172e-01,
          -1.6699e-01, -3.9062e-01]]], device='cuda:0', dtype=torch.bfloat16,
       grad_fn=<Unsloth_Offloaded_Gradient_CheckpointerBackward>)
1   : tensor([[0, 1, 1,  ..., 1, 1, 1]], device='cuda:0')
2   : tensor([[   0,    1,    2,  ..., 8381, 8382, 8383]], device='cuda:0')
3 FP: tensor([], device='cuda:0',
       grad_fn=<Unsloth_Offloaded_Gradient_CheckpointerBackward>)
4 FP: tensor([], device='cuda:0',
       grad_fn=<Unsloth_Offloaded_Gradient_CheckpointerBackward>)
5   : tensor([[  -100,      1,      3,  ..., 130418,   2613,      2]],
       device='cuda:0')
TUPLED OUTPUTS: 3 == 3!
```
Notes:

- each "batch" comes with 6 outputs, whereas 3 are "floating point" and match up with the `grad_tensors` length (3).
- the ones that are floating point have a `grad_fn`, since I need to use 'unsloth' it is using that one
- all "good" cases have 3 of these

The next (actually directly following the above log):
```
===========================================================================================
UNFILTERED OUTPUTS: 6
0 FP: tensor([[[ 0.2910,  0.8438, -0.3262,  ..., -0.0081,  0.1650,  0.4902],
         [-0.8672, -0.6523,  0.2539,  ..., -0.6641,  0.0142,  0.1309],
         [-0.3262, -0.1826, -0.0664,  ..., -0.2109, -0.5234,  0.1826],
         ...,
         [-0.4023,  0.1299, -0.1445,  ...,  0.3047,  0.5273, -0.3184],
         [-0.6562, -0.1445, -0.4082,  ..., -0.0356,  0.2676, -0.3711],
         [-0.1455,  0.4355,  0.6094,  ...,  0.1445,  0.0061, -0.5469]]],
       device='cuda:0', dtype=torch.bfloat16,
       grad_fn=<Unsloth_Offloaded_Gradient_CheckpointerBackward>)
1 FP: tensor([], device='cuda:0',
       grad_fn=<Unsloth_Offloaded_Gradient_CheckpointerBackward>)
2   : tensor([[   0,    1,    2,  ..., 8381, 8382, 8383]], device='cuda:0')
3 FP: tensor([], device='cuda:0',
       grad_fn=<Unsloth_Offloaded_Gradient_CheckpointerBackward>)
4 FP: tensor([], device='cuda:0',
       grad_fn=<Unsloth_Offloaded_Gradient_CheckpointerBackward>)
5   : tensor([[   1,    3, 1091,  ..., 4043, 1042,    2]], device='cuda:0')
TUPLED OUTPUTS: 4 == 3!
CRASHING NOW: 4 != 3
[...]
```
We have a new empty tensor that has a grad_fn which is counted in the filter and thus we get 4 outputs vs 3 grad tensors, which assert-fails. Doing a git bisect to see if this is recent qlora-pipe stuff.

**Comment by kallewoof** [comment]
The recent refactor with the layer stuff broke the deepspeed loader (it wanted more layer files than existed in the save dir), so I had to restart from scratch. Immediately noticing something peculiar: with exactly the same setup, grad tensors and outputs now count 1, not 3:
```
===========================================================================================
UNFILTERED OUTPUTS: 4
0 FP: tensor([[[ 6.8824e-25,  5.5318e-24, -2.9856e-24,  ..., -7.4963e-24,
           4.4978e-24,  2.0938e-24],
         [ 6.8824e-25,  5.5318e-24, -2.9856e-24,  ..., -7.4963e-24,
           4.4978e-24,  2.0938e-24],
         [ 6.8824e-25,  5.5318e-24, -2.9856e-24,  ..., -7.4963e-24,
           4.4978e-24,  2.0938e-24],
         ...,
         [ 6.0059e-02,  2.8687e-02, -2.5781e-01,  ..., -2.6953e-01,
           2.3633e-01,  6.7188e-01],
         [ 1.3379e-01, -2.7148e-01, -1.9922e-01,  ..., -2.9688e-01,
          -2.0703e-01,  2.1875e-01],
         [-4.1016e-02,  2.1582e-01,  2.9297e-01,  ..., -8.6914e-02,
          -2.6953e-01, -4.4531e-01]],

        [[ 6.8824e-25,  5.5318e-24, -2.9856e-24,  ..., -7.4963e-24,
           4.4978e-24,  2.0938e-24],
         [ 6.8824e-25,  5.5318e-24, -2.9856e-24,  ..., -7.4963e-24,
           4.4978e-24,  2.0938e-24],
         [ 6.8824e-25,  5.5318e-24, -2.9856e-24,  ..., -7.4963e-24,
           4.4978e-24,  2.0938e-24],
         ...,
         [-7.8613e-02, -3.2422e-01,  3.7305e-01,  ...,  9.3262e-02,
           2.9053e-02, -3.8330e-02],
         [-5.6152e-02, -3.1055e-01, -2.5586e-01,  ..., -7.7148e-02,
          -3.3398e-01, -1.1377e-01],
         [ 1.5527e-01,  4.3945e-01,  5.0391e-01,  ...,  1.8164e-01,
          -2.7344e-01, -4.4141e-01]]], device='cuda:0', dtype=torch.bfloat16,
       grad_fn=<Unsloth_Offloaded_Gradient_CheckpointerBackward>)
1   : tensor([[0, 0, 0,  ..., 1, 1, 1],
        [0, 0, 0,  ..., 1, 1, 1]], device='cuda:0')
2   : tensor([[   0,    1,    2,  ..., 6205, 6206, 6207]], device='cuda:0')
3   : tensor([[ -100,  -100,  -100,  ...,  1402,  1046,     2],
        [ -100,  -100,  -100,  ...,  1115, 10555,     2]], device='cuda:0')
TUPLED OUTPUTS: 1 == 1!
```
TBH, those 2 empty unsloth grad fn layers in above are sus.

**Comment by kallewoof** [comment]
Currently, my suspicion is 47bd0a650f9d628f00d8080da3d29c2ee13ee429 but unfortunately this commit moves things around and changes them so it's very hard to pinpoint where exactly things went wrong. Git bisect still ongoing but because I cannot reuse save points, it takes one hour for each step.

**Comment by kallewoof** [comment]
At step 94 now with no issues running on 6fb7c8e (https://github.com/tdrussell/qlora-pipe/compare/6fb7c8eeae52a0e36c41f00628985f29d8330684..main for comparison to main branch). This is definitely qlora-pipe.

**Comment by kallewoof** [comment]
Unfortunately I am out of time. I have reverted to the 6fb7c8e commit on my end for now. If I get some time to spare I will dig further. My recommendation for now is to revert and then clean up 47bd0a6, splitting it into MOVEONLY commits and actual commits that change stuff.

**Comment by jukofyork** [comment]
I am using the version from right before https://github.com/tdrussell/qlora-pipe/commit/47bd0a650f9d628f00d8080da3d29c2ee13ee429 and can confirm it seems to be running OK.

I deliberately held off upgrading as it says "tested all model types except Cohere..." and was in the process of tuning hyperparmeters for Cohere models.

**Comment by tdrussell** [comment]
Which model are you training? For llama models there are some new tensors for RoPE embeddings passed between layers, as that is the new non-deprecated way to do things. And I also updated the unsloth gradient checkpoint function. I will try to reproduce this error. Maybe the combination of those two things broke something.

**Comment by tdrussell** [comment]
Ok I think I know what's going wrong. Those logs are very helpful.
> 1   : tensor([[0, 1, 1,  ..., ]], device='cuda:0')

You have a tensor attention_mask with 0 in the first element.

> 1 FP: tensor([], device='cuda:0',
       grad_fn=<Unsloth_Offloaded_Gradient_CheckpointerBackward>)

Now, for this micro batch the model code converted the attention_mask to None, because the mask was all 1s. I was trying to handle this case more correctly, by making the attention_mask as an empty tensor as a signal to convert it back to None later where it is used (you must past tensors between layers). But this is unsound, as with pipeline parallelism the tensors must be static shape between micro batches.

Commit 19b1442 should fix this. Can you try it?

**Comment by kallewoof** [comment]
> Ok I think I know what's going wrong. Those logs are very helpful.

Happy to hear they were helpful.

> > 1   : tensor([[0, 1, 1,  ..., ]], device='cuda:0')
> 
> You have a tensor attention_mask with 0 in the first element.
> 
> > 1 FP: tensor([], device='cuda:0',
> > grad_fn=<Unsloth_Offloaded_Gradient_CheckpointerBackward>)
> 
> Now, for this micro batch the model code converted the attention_mask to None, because the mask was all 1s. I was trying to handle this case more correctly, by making the attention_mask as an empty tensor as a signal to convert it back to None later where it is used (you must past tensors between layers). But this is unsound, as with pipeline parallelism the tensors must be static shape between micro batches.

I still don't understand why it had 3 grad tensors in the new/broken code and 1 grad tensor in the old/working code. I need to look at the code again I guess. Either way, your explanation makes sense.

> Commit [19b1442](https://github.com/tdrussell/qlora-pipe/commit/19b1442a63c039b1c59bf2b370c7a9d7778326c1) should fix this. Can you try it?

Not soon, unfortunately. Will try to test it asap though.

**Comment by tdrussell** [comment]
> I still don't understand why it had 3 grad tensors in the new/broken code and 1 grad tensor in the old/working code.

This is because I added the cos and sin RoPE embedding tensors, that are passed between layers, for Llama models. This is the new way to do things in Transformers. But some other models still need the position_ids only, so the cos/sin tensors are just empty in that case. But they are floating point tensors, so they will show as requiring grad. That's where the extra 2 grad tensors are coming from.

**Comment by kallewoof** [comment]
@tdrussell Been running a test training run for some hours on latest main + my stuff and it is not crashing anymore, so your fix probably addressed. Closing this. Will reopen if I see another crash.
